apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ku001-web
  name: ku001-web
spec:
  containers:
  - image: redis
    name: cache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
