apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: test
  name: kub001
  namespace: develop
spec:
  containers:
  - image: nginx
    name: kub001
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
